# Generated by Django 4.2.5 on 2023-09-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anketa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='myapp/image/', verbose_name='Фото')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('skill_1', models.CharField(max_length=100, verbose_name='1-е умение')),
                ('skill_2', models.CharField(max_length=100, verbose_name='2-е умение')),
                ('skill_3', models.CharField(max_length=100, verbose_name='3-е умение')),
                ('skill_4', models.CharField(max_length=100, verbose_name='4-е умение')),
                ('skill_5', models.CharField(max_length=100, verbose_name='5-е умение')),
                ('about_me', models.TextField(verbose_name='Обо мне')),
            ],
        ),
    ]
